"""Project complete caller evidence into generated byte return prototypes.

Layer: Types/Lowering.
Responsibility: apply a function-wide caller-observed AL signedness proof to
generated angr Function and CFunction prototypes without changing arguments.
Consumes alias, widening, typed conditions, and Semantics return storage.
This module does not inspect assembly, source, COD, or rendered C text.

Consumes alias, widening, and typed facts. Do not recover semantics from COD,
source, assembly, or rendered C text.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Protocol, cast

from angr.sim_type import SimTypeBottom, SimTypeChar, SimTypeFunction
from archinfo import Arch

from ..semantics.terminal_return_storage import TerminalReturnStorage8616
from .explicit_char_types import explicit_scalar_char_type_8616
from .interprocedural_storage_contracts import StorageTrialSignedness8616
from .interprocedural_storage_return_trial_materialization import return_output_storages_8616
from .interprocedural_storage_return_type_collection import collect_function_return_storage_type_8616
from .interprocedural_storage_return_type_collection_contracts import (
    FunctionReturnStorageTypeResult8616,
)

__all__ = [
    "CallerObservedByteReturnTypeFailure8616",
    "CallerObservedByteReturnTypeResult8616",
    "CallerObservedByteReturnTypeVerdict8616",
    "apply_caller_observed_byte_return_type_8616",
    "materialize_caller_observed_byte_return_type_8616",
]


class CallerObservedByteReturnTypeVerdict8616(StrEnum):
    """Outcome of projecting a caller-observed AL type into a prototype."""

    NOT_APPLICABLE = "not_applicable"
    PROVEN = "proven"
    UNKNOWN_REFUSE = "unknown_refuse"
    CONFLICT = "conflict"


class CallerObservedByteReturnTypeFailure8616(StrEnum):
    """Stable reason a byte return proof was not projected."""

    EVIDENCE_REFUSED = "evidence_refused"
    FUNCTION_PROTOTYPE_CONFLICT = "function_prototype_conflict"


@dataclass(frozen=True, slots=True)
class CallerObservedByteReturnTypeResult8616:
    """Typed byte-prototype projection result with retained source evidence."""

    verdict: CallerObservedByteReturnTypeVerdict8616
    changed: bool
    evidence: FunctionReturnStorageTypeResult8616 | None
    failure: CallerObservedByteReturnTypeFailure8616 | None

    @property
    def applicable(self) -> bool:
        """Return whether AL byte projection owned this decision."""
        return self.verdict is not CallerObservedByteReturnTypeVerdict8616.NOT_APPLICABLE


class _ProjectSurface8616(Protocol):
    """Third-party project fields used for ABI-bound SimTypes."""

    arch: Arch


class _FunctionSurface8616(Protocol):
    """angr Function fields updated by caller-observed type lowering."""

    addr: int
    is_prototype_guessed: bool
    prototype: object | None


class _CodegenSurface8616(Protocol):
    """Third-party codegen fields updated after prototype refinement."""

    cfunc: object
    _inertia_codegen_decl_refresh_required_8616: bool
    _inertia_force_codegen_regeneration_8616: bool


class _CFunctionSurface8616(Protocol):
    """angr CFunction fields updated by caller-observed type lowering."""

    functy: object


def _not_applicable_8616() -> CallerObservedByteReturnTypeResult8616:
    """Return a zero-evidence result for a different terminal carrier."""
    return CallerObservedByteReturnTypeResult8616(
        CallerObservedByteReturnTypeVerdict8616.NOT_APPLICABLE,
        False,
        None,
        None,
    )


def _prototype_with_char_return_8616(
    prototype: SimTypeFunction | None,
    return_type: SimTypeChar,
    arch: Arch,
) -> SimTypeFunction:
    """Preserve every argument field while replacing only the return type."""
    return SimTypeFunction(
        list(prototype.args) if prototype is not None else [],
        return_type.with_arch(arch),
        arg_names=prototype.arg_names if prototype is not None else None,
        variadic=prototype.variadic if prototype is not None else False,
    ).with_arch(arch)


def _prototype_has_char_signedness_8616(
    prototype: object,
    return_type: SimTypeChar,
) -> bool:
    """Return whether one prototype already carries the proven char sign."""
    return bool(
        isinstance(prototype, SimTypeFunction)
        and isinstance(prototype.returnty, SimTypeChar)
        and prototype.returnty.signed is return_type.signed
    )


def _proven_char_type_8616(
    project: object,
    function_addr: int,
) -> tuple[SimTypeChar | None, FunctionReturnStorageTypeResult8616]:
    """Collect one complete caller proof and lower its signedness to C char."""
    evidence = collect_function_return_storage_type_8616(
        project,
        function_addr,
        return_output_storages_8616(TerminalReturnStorage8616.AL),
    )
    if not evidence.complete:
        return None, evidence
    signed = evidence.signedness is StorageTrialSignedness8616.SIGNED
    return (
        cast(
            SimTypeChar,
            explicit_scalar_char_type_8616(
                SimTypeChar(signed=signed).with_arch(cast(_ProjectSurface8616, project).arch)
            ),
        ),
        evidence,
    )


def apply_caller_observed_byte_return_type_8616(
    project: object,
    function: object,
    storage: TerminalReturnStorage8616 | None,
    *,
    explicit_prototype: bool,
) -> CallerObservedByteReturnTypeResult8616:
    """Refine one guessed Function prototype from complete AL caller evidence."""
    project_surface = cast(_ProjectSurface8616, project)
    function_surface = cast(_FunctionSurface8616, function)
    prototype = function_surface.prototype
    if (
        project_surface.arch.name != "86_16"
        or storage is not TerminalReturnStorage8616.AL
        or explicit_prototype
        or (
            prototype is not None
            and (
                not isinstance(prototype, SimTypeFunction)
                or not isinstance(prototype.returnty, (SimTypeBottom, SimTypeChar))
            )
        )
    ):
        return _not_applicable_8616()
    return_type, evidence = _proven_char_type_8616(project, function_surface.addr)
    if return_type is None:
        return CallerObservedByteReturnTypeResult8616(
            CallerObservedByteReturnTypeVerdict8616.UNKNOWN_REFUSE,
            False,
            evidence,
            CallerObservedByteReturnTypeFailure8616.EVIDENCE_REFUSED,
        )
    typed_prototype = prototype if isinstance(prototype, SimTypeFunction) else None
    replacement = _prototype_with_char_return_8616(typed_prototype, return_type, project_surface.arch)
    changed = not _prototype_has_char_signedness_8616(prototype, return_type)
    function_surface.prototype = replacement
    return CallerObservedByteReturnTypeResult8616(
        CallerObservedByteReturnTypeVerdict8616.PROVEN,
        changed,
        evidence,
        None,
    )


def materialize_caller_observed_byte_return_type_8616(
    project: object,
    codegen: object,
    function: object,
    storage: TerminalReturnStorage8616 | None,
    *,
    explicit_prototype: bool,
) -> CallerObservedByteReturnTypeResult8616:
    """Refine coherent Function and CFunction byte return prototypes."""
    project_surface = cast(_ProjectSurface8616, project)
    codegen_surface = cast(_CodegenSurface8616, codegen)
    function_surface = cast(_FunctionSurface8616, function)
    cfunc = cast(_CFunctionSurface8616, codegen_surface.cfunc)
    codegen_prototype = cfunc.functy
    if (
        project_surface.arch.name != "86_16"
        or storage is not TerminalReturnStorage8616.AL
        or explicit_prototype
        or not isinstance(codegen_prototype, SimTypeFunction)
        or not isinstance(codegen_prototype.returnty, SimTypeChar)
    ):
        return _not_applicable_8616()
    function_prototype = function_surface.prototype
    if function_prototype is not None and (
        not isinstance(function_prototype, SimTypeFunction)
        or not isinstance(function_prototype.returnty, (SimTypeBottom, SimTypeChar))
    ):
        return CallerObservedByteReturnTypeResult8616(
            CallerObservedByteReturnTypeVerdict8616.CONFLICT,
            False,
            None,
            CallerObservedByteReturnTypeFailure8616.FUNCTION_PROTOTYPE_CONFLICT,
        )
    return_type, evidence = _proven_char_type_8616(project, function_surface.addr)
    if return_type is None:
        return CallerObservedByteReturnTypeResult8616(
            CallerObservedByteReturnTypeVerdict8616.UNKNOWN_REFUSE,
            False,
            evidence,
            CallerObservedByteReturnTypeFailure8616.EVIDENCE_REFUSED,
        )
    replacement = _prototype_with_char_return_8616(
        codegen_prototype,
        return_type,
        project_surface.arch,
    )
    typed_function_prototype = (
        function_prototype if isinstance(function_prototype, SimTypeFunction) else codegen_prototype
    )
    function_replacement = _prototype_with_char_return_8616(
        typed_function_prototype,
        return_type,
        project_surface.arch,
    )
    changed = not _prototype_has_char_signedness_8616(
        cfunc.functy,
        return_type,
    ) or not _prototype_has_char_signedness_8616(
        function_surface.prototype,
        return_type,
    )
    cfunc.functy = replacement
    function_surface.prototype = function_replacement
    if changed:
        codegen_surface._inertia_codegen_decl_refresh_required_8616 = True
        codegen_surface._inertia_force_codegen_regeneration_8616 = True
    return CallerObservedByteReturnTypeResult8616(
        CallerObservedByteReturnTypeVerdict8616.PROVEN,
        changed,
        evidence,
        None,
    )
