// SORTD.globals.c
// Generated by decompiling SORTD.EXE
// using Reko decompiler version 0.12.4.0.

#include "SORTD.h"

struct Eq_8973 * g_ptr0000; // 00000000
struct Eq_3943 * g_ptrADDCAFE0; // ADDCAFE0
