def address_width_bits(mode32: bool, chsz_ad: bool = ...) -> int: ...


def decode_width_profile(mode32: bool, chsz_op: bool = ..., chsz_ad: bool = ...) -> WidthProfile: ...


def operand_width_bits(mode32: bool, chsz_op: bool = ...) -> int: ...
