def register_domain_for_name(name: str | None) -> DomainKey | None: ...


def register_pair_name(name: str | None) -> str | None: ...


def register_view_for_name(name: str | None) -> View | None: ...


class View:
    @property
    def bit_end(self) -> int: ...
    def can_join(self, other: 'View') -> bool: ...
