from angr.analyses.decompiler.structured_codegen.c import (
    CBinaryOp,
    CVariable,
)


def _alias_identity_for_variable(
    variable: <class 'Union'>[angr.sim_variable.SimRegisterVariable, angr.sim_variable.SimMemoryVariable, angr.sim_variable.SimStackVariable]
) -> tuple[str, Any] | None: ...


def _canonical_stack_base(base: str | None) -> str: ...


def _merge_storage_domains(
    existing: _StorageDomainSignature | None,
    incoming: _StorageDomainSignature
) -> _StorageDomainSignature: ...


def _mk_fp_components(expr: CBinaryOp) -> tuple[int, int] | None: ...


def _stack_slot_identity_for_variable(
    variable: <class 'Union'>[None, angr.sim_variable.SimStackVariable]
) -> _StackSlotIdentity | None: ...


def _storage_domain_for_expr(
    expr: <class 'Union'>[angr.analyses.decompiler.structured_codegen.c.CBinaryOp, angr.analyses.decompiler.structured_codegen.c.CVariable]
) -> _StorageDomainSignature: ...


def _storage_domain_for_variable(
    variable: <class 'Union'>[angr.sim_variable.SimRegisterVariable, angr.sim_variable.SimMemoryVariable, angr.sim_variable.SimStackVariable]
) -> _StorageDomainSignature: ...


def _storage_view_for_variable(
    variable: <class 'Union'>[angr.sim_variable.SimRegisterVariable, angr.sim_variable.SimMemoryVariable, angr.sim_variable.SimStackVariable]
) -> _StorageView: ...


def _unwrap_c_casts(
    expr: <class 'Union'>[angr.analyses.decompiler.structured_codegen.c.CBinaryOp, angr.analyses.decompiler.structured_codegen.c.CVariable]
) -> <class 'Union'>[angr.analyses.decompiler.structured_codegen.c.CBinaryOp, angr.analyses.decompiler.structured_codegen.c.CVariable]: ...


def can_join_alias_storage(
    lhs: CVariable,
    rhs: CVariable
) -> bool: ...


def describe_alias_storage(
    expr: <class 'Union'>[angr.analyses.decompiler.structured_codegen.c.CBinaryOp, angr.analyses.decompiler.structured_codegen.c.CVariable]
) -> AliasStorageFacts: ...


def same_alias_storage_domain(
    lhs: CVariable,
    rhs: CVariable
) -> bool: ...


class AliasStorageFacts:
    def can_join(self, other: 'AliasStorageFacts') -> bool: ...
    def compatible_view(self, other: 'AliasStorageFacts') -> bool: ...
    def needs_synthesis(self) -> bool: ...
    def same_domain(self, other: 'AliasStorageFacts') -> bool: ...


class _StackSlotIdentity:
    def __post_init__(self) -> None: ...
    def can_join(self, other: '_StackSlotIdentity') -> bool: ...
    def end_offset(self) -> int | None: ...
    def join(self, other: '_StackSlotIdentity') -> '_StackSlotIdentity | None': ...


class _StorageDomainSignature:
    def can_join(self, other: '_StorageDomainSignature') -> bool: ...
    def is_const(self) -> bool: ...
    def is_mixed(self) -> bool: ...
    def is_unknown(self) -> bool: ...
    def join(self, other: '_StorageDomainSignature') -> '_StorageDomainSignature | None': ...


class _StorageView:
    def can_join(self, other: '_StorageView') -> bool: ...
    def end_bit(self) -> int | None: ...
    def join(self, other: '_StorageView') -> '_StorageView | None': ...
