def _make_exe_load_params_type() -> SimStruct: ...


def _make_ovl_header_type() -> SimTypePointer: ...


def _make_ovl_load_params_type() -> SimStruct: ...


def _make_slot_array_type() -> SimTypePointer: ...


def _make_sregs_type() -> SimStruct: ...


def _make_union_regs_type() -> SimUnion: ...


def _type_name(type_obj: object) -> str: ...
