def _build_decompiler_structuring_passes(
) -> Tuple[DecompilerStructuringPassSpec, DecompilerStructuringPassSpec, DecompilerStructuringPassSpec, DecompilerStructuringPassSpec, DecompilerStructuringPassSpec, DecompilerStructuringPassSpec, DecompilerStructuringPassSpec, DecompilerStructuringPassSpec, DecompilerStructuringPassSpec]: ...


def apply_x86_16_decompiler_structuring() -> None: ...
