class EquivalenceClass:
    def add_expression(self, expr: str) -> None: ...
    def add_type_constraint(self, constraint: str) -> None: ...
    def merge(self, other: EquivalenceClass) -> None: ...


class EquivalenceClassBuilder:
    def __init__(self) -> None: ...
    def build(self, expressions: list[str]) -> dict[int, EquivalenceClass]: ...
    def merge_classes(self, expr1: str, expr2: str) -> None: ...


class ExpressionNormalizer:
    def normalize(self, expr: str) -> ExpressionPattern: ...


class TypeCollector:
    def collect(self, expr_classes: dict[int, EquivalenceClass]) -> None: ...


class TypeVariableReplacer:
    def replace(self, expr_classes: dict[int, EquivalenceClass]) -> dict[int, str]: ...
