def _register_domain_and_view(variable: SimRegisterVariable) -> tuple[DomainKey | None, object | None]: ...


def _register_pair_name_for_variable(variable: SimRegisterVariable) -> str | None: ...


class RegisterWideningCandidate:
    @classmethod
    def from_expr(cls, expr: object) -> 'RegisterWideningCandidate': ...
    def is_joinable_with(self, other: 'RegisterWideningCandidate') -> bool: ...
